#!/usr/bin/python
#
#   Copyright 2012 Martijn Grendelman <m@rtijn.net>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import os.path
import sys
import argparse
import signal

my_dir = os.path.dirname(os.path.realpath(os.path.abspath(__file__)))
app_dir = os.path.join(my_dir, "taggert")
data_dir = os.path.join(my_dir, "taggert/data")
sys.path.append(app_dir)

from taggert.app import App

def process_options():
    parser = argparse.ArgumentParser(description='Taggert geotagging application',
        formatter_class=lambda prog: argparse.ArgumentDefaultsHelpFormatter(prog,max_help_position=36))
    parser.add_argument('-g', '--google', action='store_true', dest='google', help='enable map sources from Google')
    return parser.parse_args()

def handle_signal(sig, _frame):
    if sig == signal.SIGINT:
        print "Interrupted"
        app.quit()

args = process_options()
app = App(data_dir, args)
signal.signal (signal.SIGINT, handle_signal)
app.main()
